services:
  - type: web
    name: udemy-course-enroller
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 300 --max-requests 20 --max-requests-jitter 2 --worker-class sync --worker-connections 5 --preload --limit-request-line 2048 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PROXY_URL
        value: ""
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"