services:
  - type: web
    name: udemy-course-enroller
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 120 --max-requests 100 --max-requests-jitter 10 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PROXY_URL
        value: ""  # Add proxy URL here if needed