services:
  - type: web
    name: udemy-course-enroller
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 180 --max-requests 30 --max-requests-jitter 3 --worker-class sync --worker-connections 8 --preload wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PROXY_URL
        value: ""
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"